services:
  traefik:
    image: traefik:v2.11
    container_name: traefik
    command:
      - "--configFile=/etc/traefik/traefik.yml"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./letsencrypt:/letsencrypt
    networks:
      - app-net
    restart: unless-stopped

  data-api:
    build:
      context: ./apps/data-api
      dockerfile: Dockerfile
    env_file:
      - ./apps/data-api/.env.prod
    networks:
      - app-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dataapi.rule=Host(`data-api.gamecore.co.kr`)"
      - "traefik.http.services.dataapi.loadbalancer.server.port=3000"
      - "traefik.http.routers.dataapi.tls.certresolver=letsencrypt"
    restart: unless-stopped

  admin-api:
    build:
      context: ./apps/admin-api
      dockerfile: Dockerfile
    env_file:
      - ./apps/admin-api/.env.prod
    networks:
      - app-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adminapi.rule=Host(`admin-api.gamecore.co.kr`)"
      - "traefik.http.services.adminapi.loadbalancer.server.port=3000"
      - "traefik.http.routers.adminapi.tls.certresolver=letsencrypt"
    restart: unless-stopped

  auth-api:
    build:
      context: ./apps/auth-api
      dockerfile: Dockerfile
    env_file:
      - ./apps/auth-api/.env.prod
    networks:
      - app-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.authapi.rule=Host(`auth-api.gamecore.co.kr`)"
      - "traefik.http.services.authapi.loadbalancer.server.port=3000"
      - "traefik.http.routers.authapi.tls.certresolver=letsencrypt"
    restart: unless-stopped

  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    depends_on:
      - admin-api
      - auth-api
      - data-api
    networks:
      - app-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`gamecore.co.kr`) || HostRegexp(`{subdomain:[a-z0-9]+}.gamecore.co.kr`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"
      - "traefik.http.routers.frontend.tls.certresolver=letsencrypt"
    restart: unless-stopped

networks:
  app-net:
    driver: bridge
