global:
  checkNewVersion: false
  sendAnonymousUsage: false

serversTransport:
  insecureSkipVerify: true

api:
  dashboard: true
  debug: true
  insecure: false

entryPoints:
  web:
    address: ":80"

  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: gamecoregg-monorepo_app-net

certificatesResolvers:
  letsencrypt:
    acme:
      tlsChallenge: {}
      email: grooveturtle29@gmail.com
      storage: /letsencrypt/acme.json
      caServer: https://acme-v02.api.letsencrypt.org/directory

# HTTP to HTTPS 리다이렉션 미들웨어 추가
http:
  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: true
